#by @Depriced & @Illya_einzbern

from .. import loader
from asyncio import sleep 

class OxxxyMod(loader.Module):
    strings = {"name": "Oxxxy"}
    
    async def Oxxxycmd(self, message):
        await message.edit("- Салют, представьтесь пожалуйста.")
        await sleep(1)
        await message.respond("- Фёдоров Мирон Янович - некий Оксимирон.")
        await sleep(1)
        await message.respond("- Кто сегодня твой противник?")
        await sleep(1)
        await message.respond("- М, печалька, печальная.")
        await sleep(2)
        await message.respond("Говно залупа хер,")
        await sleep(1)
        await message.respond("давалка хуй блядина.")
        await sleep(1)
        await message.respond("Головка шлюха,")
        await sleep(1)
        await message.respond("член пенис.")
        await sleep(1)
        await message.respond("Рукаблуд ссанина,")
        await sleep(1)
        await message.respond("очко блядун вагина.")
        await sleep(1)
        await message.respond("Сука ебланище влагалище,")
        await sleep(1)
        await message.respond("пердун дрочила.")
        await sleep(2)
        await message.respond("Говно, хер - хер.")
        await sleep(1)
        await message.respond("Рукаблуд ссанина,")
        await sleep(1)
        await message.respond("очко блядун вагина.")
        await sleep(1)
        await message.respond("Сука ебланище влагалище,")
        await sleep(1)
        await message.respond("пердун дрочила.")
        await sleep(1)
        await message.respond("Пидор пизда, туз малафья,")
        await sleep(1)
        await message.respond("гомик мудила пилотка манда.")
        await sleep(1)
        await message.respond("Анус ванига птн пдрл шлв хуила мшнк елда, раунд!")
        await sleep(1)
        await message.respond("Говно залупа хер,")
        await sleep(1)
        await message.respond("давалка хуй блядина.")
        await sleep(1)
        await message.respond("Головка шлюха,")
        await sleep(1)
        await message.respond("член пенис.")
        await sleep(1)
        await message.respond("Пенис член шлюха,")
        await sleep(1)
        await message.respond("головка хуй залупа.")
        await sleep(1)
        await message.respond("Хер, хер - хуй,")
        await sleep(1)
        await message.respond("Хер, хер - хуй.")
        await sleep(1)
        await message.respond("Рукаблуд ссанина,")
        await sleep(1)
        await message.respond("очко блядун вагина.")
        await sleep(1)
        await message.respond("Сука ебланище влагалище,")
        await sleep(1)
        await message.respond("пердун дрочила.")
        await sleep(1)
        await message.respond("Пидор пизда, туз малафья,")
        await sleep(1)
        await message.respond("гомик мудила пилотка манда.")
        await sleep(1)
        await message.respond("Анус ванига птн пдрл шлв хуила мшнк елда, раунд!")
        await sleep(1)
        await message.respond("-Оххо, это был версус баттл и победил Оксимирон.")
        await sleep(2)
        await message.respond("Oxxxymiron - Im a шлюха girl /// by @Depriced")
        await sleep(2)
